### ISSUE TITLE
Thumbor.key global value is set in Thumbor::CryptoURL initializer

### ISSUE THREAD

**Issue by bgentry** [thumbor/ruby-thumbor#15]
This can cause weird behavior in specs or other environments where the key might change. It's also not a good practice for ruby.

https://github.com/thumbor/ruby-thumbor/blob/b2cfed1812e781a205ac000100dae297f58e8d0a/lib/thumbor/crypto_url.rb#L11

**Comment by guilhermef** [comment]
I agree with you, but we deal with the idea of an unique thumbor server per environment.
Do you have multiple thumbor servers ?

**Comment by bgentry** [comment]
We might have multiple servers. But in particular this is causing very weird behavior in our specs where we're trying to test the URLs generated in different environments (some with keys, some without). We end up with order-dependent tests because the last change to `Thumbor.key` wins.

Instead of setting `Thumbor.key`, why not just use an instance variable `@key` in the `Thumbor::CryptoURL` class?

**Comment by guilhermef** [comment]
That should work: https://github.com/thumbor/ruby-thumbor/commit/2beafa59a67c38d049a1f5eed05bfd58474c938c

I'll just wait for travis, then release a 2.0 version.

**Comment by guilhermef** [comment]
@bgentry I've released the 2.0 version: https://rubygems.org/gems/ruby-thumbor/versions/2.0.0
Thanks for the feedback.

**Comment by bgentry** [comment]
@guilhermef thanks!! :v:
